server:
  port: 8050
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_product_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.username}
  config:
    import: configserver:http://localhost:8888
