server:
  port: 8040
spring:
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      username: ecom-app
      password: ecom-app@12345
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  application:
    name: notification-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.isaachome.ecom.kafka.order.OrderConfirmation,paymentConfirmation:com.isaachome.ecom.kafka.payment.PaymentConfirmation
  mail:
    host: localhost
    username: admin
    password: admin
    port: 1025
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled:true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
